insert into UserProfile (Name, FirebaseUserId, Email) values ('Valeria D''Ugo', 'ddqhntas45flooe1u894w3cw7', 'vdugo0@so-net.ne.jp');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Filberte Tapner', 'r396zi410kirsa078wmr3mltu', 'ftapner1@seesaa.net');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Terrence Petters', '5286m5l20a0eucrs0fsvvubou', 'tpetters2@tiny.cc');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Estele McMenamie', 'yxzd14whvyl429xse7x9a8uyc', 'emcmenamie3@tinypic.com');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Florian Abba', 'xaxxcpra8g1yp3skg8a5u62ft', 'fabba4@who.int');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Boony Couth', '47snduojzt5ctqy68kppum71f', 'bcouth5@goo.gl');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Vassily Ganiford', 'obx26oz6zouk20b09cgrthl6m', 'vganiford6@linkedin.com');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Riva Barbrick', 'vhwf45kyz3fcup0e44by8d5b9', 'rbarbrick7@businessinser.com');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Eba Wasmer', 'er7gnr8ght39ier9gldty797p', 'ewasmer8@nps.gov');
insert into UserProfile (Name, FirebaseUserId, Email) values ('Yorgo Shardlow', 'lyywx4xzv8bn5phxxs7o84tss', 'yshardlow9@joomla.org');

insert into Website (Name, Url) values ('Netflix', 'https://www.netflix.com/');
insert into Website (Name, Url) values ('Hulu', 'https://www.hulu.com/');
insert into Website (Name, Url) values ('Disney+', 'https://www.disneyplus.com/');
insert into Website (Name, Url) values ('Crunchyroll', 'https://www.crunchyroll.com/');
insert into Website (Name, Url) values ('Peacock', 'https://www.peacocktv.com/');

insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (4, '30', '4/25/2022', 12.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (3, '30', '4/25/2022', 14.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (2, '30', '4/25/2022', 9.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (1, '30', '4/25/2022', 14.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (2, '30', '4/25/2022', 12.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (2, '30', '4/25/2022', 9.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (2, '30', '4/25/2022', 14.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (1, '30', '4/25/2022', 14.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (4, '30', '4/25/2022', 12.99);
insert into Trial (WebsiteId, TrialDuration, TrialExpirationDate, SubscriptionPrice) values (3, '30', '4/25/2022', 12.99);

insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (3, 1, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (9, 5, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 2, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (10, 9, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 3, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (2, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (9, 9, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 1, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (3, 7, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (7, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 2, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (7, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (2, 6, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 5, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (10, 9, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (5, 5, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (6, 9, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (5, 10, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (2, 1, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (3, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (3, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (1, 7, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (8, 4, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (4, 5, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (5, 2, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (5, 9, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (1, 8, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (1, 3, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (10, 7, '4/26/2022', 0);
insert into UserTrial (UserId, TrialId, TrialStartDate, SubscriptionActive) values (9, 4, '4/26/2022', 0);
